services:
  app:
    build: .
    container_name: noshow-iq-api
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017/noshow_iq
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: noshow-iq-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: noshow-iq-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo

volumes:
  mongo_data: